### ISSUE TITLE
1.16.5 Server crash when placing Zycraft Soil

### ISSUE THREAD

**Issue by WeasleyWalls** [nikita488/ZYCraft#18] opened 2021-10-19 15:22 UTC
Server crashes whenever one of our players place Zycraft soil and it just spams 2800 lines of the same 2 functions as you can see in the below attachment. Gonna try to get more info from the player about how and where he placed it.

Minecraft Version: 1.16.5
Modpack: ATM6 1.8.7
Forge Version: 36.2.6

https://pastebin.com/XUGatwwM

**Comment by nikita488** [comment] 2021-10-20 20:39
Interesting, i really need some screenshots of the specific setup or at least how to reproduce it, because Soil was always worked pretty well, i believe there something weird was placed on top of the Soil.

**Comment by WeasleyWalls** [comment] 2021-10-20 22:41
After talking with the user and remaking the farm he did we narrowed it down to activating farm blocks with redstone. We built a 3x3x3 with hollow centre and put carrots on them. After that I put a lever on the side and activated it which crashed the server.

**Comment by nikita488** [comment] 2021-10-21 08:31
Is it the right setup? Because i activated the lever and i can't reproduce the crash for some reason :/
![image](https://user-images.githubusercontent.com/6237881/138241071-bed3d3c7-12eb-49e7-9322-1909681bafd6.png)

**Comment by WeasleyWalls** [comment] 2021-10-22 19:50
After testing it again you need to have it on stone bricks. Not a clue why this is the case or if any other blocks act the same but they crashed it for me

**Comment by nikita488** [comment] 2021-10-22 20:38
Fixed in 3.1.3

**Closed as completed** 2021-10-22 20:37 UTC
